title = "InfiniteMath"
gitRepoUrl = "https://github.com/KdudeDev/InfiniteMath"

classOrder = []
gitSourceBranch = "main"
changelog = true

[docusaurus]
url = "https://KdudeDev.github.io/"
baseUrl = "/InfiniteMath/"  
tagline = "InfiniteMath allows you to surpass the 10^308 limit."
favicon = "/favicon.png"

[navbar]
title = ""

[navbar.logo]
src = "/logo.png"

[home]

enabled = true
includeReadme = false

[footer]
style = "dark"
copyright = "Copyright © 2023 KdudeDev"
